Q1

In [1]:
import numpy as np


arr1 = np.arange(5, 26)
print("1.1 1D Array from 5 to 25:\n", arr1)


arr2 = np.random.randint(10, 51, size=(3, 4))
print("\n1.2 2D Random Array (3x4):\n", arr2)


1.1 1D Array from 5 to 25:
 [ 5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25]

1.2 2D Random Array (3x4):
 [[39 31 42 16]
 [35 44 43 36]
 [25 10 35 41]]


Q2

In [2]:

print("2.1 Attributes of arr1:")
print("Shape:", arr1.shape)
print("Size:", arr1.size)
print("Data type:", arr1.dtype)


print("\n2.2 Attributes of arr2:")
print("Shape:", arr2.shape)
print("Size:", arr2.size)
print("Data type:", arr2.dtype)


2.1 Attributes of arr1:
Shape: (21,)
Size: 21
Data type: int32

2.2 Attributes of arr2:
Shape: (3, 4)
Size: 12
Data type: int32


Q3

In [3]:

Array1 = np.array([2, 4, 6, 8, 10])
Array2 = np.array([1, 3, 5, 7, 9])


print("3.2 Array Operations:")
print("Addition:", Array1 + Array2)
print("Subtraction:", Array1 - Array2)
print("Element-wise Multiplication:", Array1 * Array2)
print("Element-wise Division:", Array1 / Array2)


3.2 Array Operations:
Addition: [ 3  7 11 15 19]
Subtraction: [1 1 1 1 1]
Element-wise Multiplication: [ 2 12 30 56 90]
Element-wise Division: [2.         1.33333333 1.2        1.14285714 1.11111111]


Q4

In [4]:

arr3 = np.arange(1, 10).reshape(3, 3)
print("4.1 2D Array (3x3):\n", arr3)


print("\n4.2 After Broadcasting (arr3 * 5):\n", arr3 * 5)


4.1 2D Array (3x3):
 [[1 2 3]
 [4 5 6]
 [7 8 9]]

4.2 After Broadcasting (arr3 * 5):
 [[ 5 10 15]
 [20 25 30]
 [35 40 45]]


Q5

In [6]:

arr4 = np.arange(10, 26).reshape(4, 4)
print("5.1 2D Array (4x4):\n", arr4)


print("\n5.2 Second Row:", arr4[1])
print("5.2 Last Column:", arr4[:, -1])


arr4[0] = 0
print("\n5.3 After Replacing First Row with Zeros:\n", arr4)


5.1 2D Array (4x4):
 [[10 11 12 13]
 [14 15 16 17]
 [18 19 20 21]
 [22 23 24 25]]

5.2 Second Row: [14 15 16 17]
5.2 Last Column: [13 17 21 25]

5.3 After Replacing First Row with Zeros:
 [[ 0  0  0  0]
 [14 15 16 17]
 [18 19 20 21]
 [22 23 24 25]]


Q6

In [7]:
import numpy as np


arr6 = np.random.randint(20, 41, size=10)
print("6.1 Array:", arr6)


print("6.2 Elements greater than 30:", arr6[arr6 > 30])


6.1 Array: [34 23 34 21 39 35 36 27 22 33]
6.2 Elements greater than 30: [34 34 39 35 36 33]


Q7

In [8]:

arr7 = np.arange(11, 23)
print("7.1 1D Array:", arr7)


reshaped_arr7 = arr7.reshape(3, 4)
print("\n7.2 Reshaped Array (3x4):\n", reshaped_arr7)


7.1 1D Array: [11 12 13 14 15 16 17 18 19 20 21 22]

7.2 Reshaped Array (3x4):
 [[11 12 13 14]
 [15 16 17 18]
 [19 20 21 22]]


Q8

In [9]:

A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

print("8.1 Matrix A:\n", A)
print("Matrix B:\n", B)


print("\n8.2 Matrix Multiplication:\n", np.dot(A, B))
print("\nTranspose of Matrix A:\n", A.T)


8.1 Matrix A:
 [[1 2]
 [3 4]]
Matrix B:
 [[5 6]
 [7 8]]

8.2 Matrix Multiplication:
 [[19 22]
 [43 50]]

Transpose of Matrix A:
 [[1 3]
 [2 4]]


Q9

In [10]:

arr9 = np.random.randint(10, 61, size=15)
print("9.1 Array:", arr9)


print("\n9.2 Mean:", np.mean(arr9))
print("Median:", np.median(arr9))
print("Standard Deviation:", np.std(arr9))


9.1 Array: [38 37 45 52 37 44 39 12 24 41 20 59 23 17 37]

9.2 Mean: 35.0
Median: 37.0
Standard Deviation: 12.81145320927073


Q10

In [11]:

A = np.array([[2, 1, 3],
              [0, 5, 6],
              [7, 8, 9]])
print("10.1 Matrix A:\n", A)


print("\nDeterminant of A:", np.linalg.det(A))
print("Inverse of A:\n", np.linalg.inv(A))
eigenvalues, eigenvectors = np.linalg.eig(A)
print("\nEigenvalues:", eigenvalues)
print("Eigenvectors:\n", eigenvectors)


10.1 Matrix A:
 [[2 1 3]
 [0 5 6]
 [7 8 9]]

Determinant of A: -68.99999999999996
Inverse of A:
 [[ 0.04347826 -0.2173913   0.13043478]
 [-0.60869565  0.04347826  0.17391304]
 [ 0.50724638  0.13043478 -0.14492754]]

Eigenvalues: [15.45215427  2.40475147 -1.85690573]
Eigenvectors:
 [[-0.22453607 -0.55941438 -0.38300969]
 [-0.48513596  0.7607706  -0.60830181]
 [-0.84511931 -0.3290648   0.69517803]]


Q11

In [12]:

positions = np.array([(0,0), (2,3), (4,7), (7,10), (10,15)])


dist = np.linalg.norm(positions[-1] - positions[0])
print("11.1 Euclidean distance (first to last):", dist)


step_distances = np.linalg.norm(np.diff(positions, axis=0), axis=1)
total_distance = np.sum(step_distances)
print("11.2 Total distance traveled:", total_distance)


11.1 Euclidean distance (first to last): 18.027756377319946
11.2 Total distance traveled: 18.151279812428157
